### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by xieguanliang** [githubliruiyuan/Animation#1]
快速滑动的时候，第三个页面出现空指针(E/MessageQueue-JNI: java.lang.NullPointerException lry.cn.animation.guide.MainActivity.animal(MainActivity.java:290))，因为handler延迟一秒，才执行动画，当动画没有开始执行的时候，进入了case  3：  3_icon2.getAnimation().cancel()导致的，所以要在前面加上一句判断， if (t3_icon2.getAnimation()!=null)，下面的几个都是。

**Comment by githubliruiyuan** [comment]
谢谢@xieguanliang指出的问题以及修改方法，一直没有时间修改
